import type {
  EnvironmentReport,
  RuntimeSchema,
  SettingCapability,
  SettingRestriction,
  SnapshotInfo,
} from "./types";

function controlCapability(
  overrides: Partial<SettingCapability> = {},
): SettingCapability {
  return {
    editMode: "control",
    reason: null,
    activation: "reload",
    constraintBehavior: "reject",
    min: null,
    max: null,
    step: null,
    unit: null,
    platform: null,
    ...overrides,
  };
}

function referenceCapability(reason: Exclude<SettingRestriction, null>): SettingCapability {
  return {
    editMode: "none",
    reason,
    activation: "unknown",
    constraintBehavior: "unknown",
    min: null,
    max: null,
    step: null,
    unit: null,
    platform: null,
  };
}

export const demoEnvironment: EnvironmentReport = {
  platform: "macOS",
  architecture: "arm64",
  ghostty: {
    available: true,
    version: "1.3.1",
    channel: "stable",
  },
  candidates: [
    {
      id: "demo-app-support",
      label: "macOS · config",
      source: "macos",
      format: "legacy",
      priority: 3,
      exists: true,
      writable: true,
      symlink: false,
      sizeBytes: 1928,
      creationEligible: false,
    },
    {
      id: "demo-xdg",
      label: "XDG · config",
      source: "xdg",
      format: "legacy",
      priority: 1,
      exists: true,
      writable: true,
      symlink: false,
      sizeBytes: 5145,
      creationEligible: false,
    },
  ],
  warnings: [],
};

export const demoSchema: RuntimeSchema = {
  ghosttyVersion: "1.3.1",
  schemaHash: "demo",
  diagnostics: ["正在使用演示数据。"],
  options: [
    {
      key: "theme",
      description: "选择 Ghostty 主题，也可以分别设置浅色和深色主题。",
      defaultValues: ["dark:Catppuccin Mocha,light:Catppuccin Latte"],
      currentValues: ["dark:Catppuccin Mocha,light:Catppuccin Latte"],
      category: "appearance",
      kind: "select",
      choices: [
        "dark:Catppuccin Mocha,light:Catppuccin Latte",
        "TokyoNight",
        "Dracula",
        "Rose Pine",
        "Gruvbox Dark Hard",
      ],
      repeatable: false,
      platform: null,
      since: null,
      risk: "sensitive",
      editable: false,
      capability: referenceCapability("needs-theme-picker"),
    },
    {
      key: "background",
      description: "终端背景色。",
      defaultValues: ["1e1e2e"],
      currentValues: ["1e1e2e"],
      category: "appearance",
      kind: "color",
      choices: [],
      repeatable: false,
      platform: null,
      since: null,
      risk: "normal",
      editable: true,
      capability: controlCapability(),
    },
    {
      key: "foreground",
      description: "终端文字颜色。",
      defaultValues: ["cdd6f4"],
      currentValues: ["cdd6f4"],
      category: "appearance",
      kind: "color",
      choices: [],
      repeatable: false,
      platform: null,
      since: null,
      risk: "normal",
      editable: true,
      capability: controlCapability(),
    },
    {
      key: "background-opacity",
      description: "背景不透明度：0 为完全透明，1 为完全不透明。",
      defaultValues: ["1"],
      currentValues: ["0.94"],
      category: "appearance",
      kind: "number",
      choices: [],
      repeatable: false,
      platform: null,
      since: null,
      risk: "normal",
      editable: true,
      capability: controlCapability({
        activation: "restart",
        constraintBehavior: "clamp",
        min: 0,
        max: 1,
        step: 0.01,
        unit: "percent",
      }),
    },
    {
      key: "background-image",
      description: "使用本地 PNG 或 JPEG 文件作为终端背景。",
      defaultValues: [""],
      currentValues: [],
      category: "appearance",
      kind: "text",
      choices: [],
      repeatable: false,
      platform: null,
      since: "1.2.0",
      risk: "normal",
      editable: false,
      capability: {
        ...referenceCapability("needs-editor"),
        activation: "reload",
        constraintBehavior: "reject",
      },
    },
    {
      key: "background-image-opacity",
      description: "调整背景图片相对于窗口背景的可见程度。",
      defaultValues: ["1"],
      currentValues: ["1"],
      category: "appearance",
      kind: "number",
      choices: [],
      repeatable: false,
      platform: null,
      since: "1.2.0",
      risk: "normal",
      editable: true,
      capability: controlCapability({ min: 0, step: 0.01, unit: "percent" }),
    },
    {
      key: "background-image-fit",
      description: "选择背景图片如何适应终端区域。",
      defaultValues: ["contain"],
      currentValues: ["contain"],
      category: "appearance",
      kind: "select",
      choices: ["contain", "cover", "stretch", "none"],
      repeatable: false,
      platform: null,
      since: "1.2.0",
      risk: "normal",
      editable: true,
      capability: controlCapability(),
    },
    {
      key: "background-image-position",
      description: "选择背景图片在终端区域中的对齐位置。",
      defaultValues: ["center"],
      currentValues: ["center"],
      category: "appearance",
      kind: "select",
      choices: ["top-left", "top-center", "top-right", "center-left", "center", "center-right", "bottom-left", "bottom-center", "bottom-right"],
      repeatable: false,
      platform: null,
      since: "1.2.0",
      risk: "normal",
      editable: true,
      capability: controlCapability(),
    },
    {
      key: "background-image-repeat",
      description: "图片未填满终端时重复显示。",
      defaultValues: ["false"],
      currentValues: ["false"],
      category: "appearance",
      kind: "boolean",
      choices: [],
      repeatable: false,
      platform: null,
      since: "1.2.0",
      risk: "normal",
      editable: true,
      capability: controlCapability(),
    },
    {
      key: "font-family",
      description: "终端字体，可以配置多个备用字体。",
      defaultValues: ["JetBrains Mono"],
      currentValues: ["JetBrains Mono"],
      category: "font",
      kind: "select",
      choices: ["JetBrains Mono", "Berkeley Mono", "SF Mono", "Fira Code"],
      repeatable: true,
      platform: null,
      since: null,
      risk: "normal",
      editable: false,
      capability: referenceCapability("needs-list-editor"),
    },
    {
      key: "font-size",
      description: "终端字号，单位为磅（pt）。",
      defaultValues: ["13"],
      currentValues: ["14"],
      category: "font",
      kind: "number",
      choices: [],
      repeatable: false,
      platform: null,
      since: null,
      risk: "normal",
      editable: true,
      capability: controlCapability({ min: 1, max: 255, step: 0.5, unit: "pt" }),
    },
    {
      key: "cursor-style",
      description: "光标形状。",
      defaultValues: ["block"],
      currentValues: ["block"],
      category: "cursor",
      kind: "select",
      choices: ["block", "bar", "underline", "block_hollow"],
      repeatable: false,
      platform: null,
      since: null,
      risk: "normal",
      editable: true,
      capability: controlCapability(),
    },
    {
      key: "cursor-style-blink",
      description: "让光标闪烁。",
      defaultValues: ["false"],
      currentValues: ["true"],
      category: "cursor",
      kind: "boolean",
      choices: ["true", "false"],
      repeatable: false,
      platform: null,
      since: null,
      risk: "normal",
      editable: true,
      capability: controlCapability(),
    },
    {
      key: "window-padding-x",
      description: "窗口左右留白。",
      defaultValues: ["0"],
      currentValues: ["12"],
      category: "window",
      kind: "integer",
      choices: [],
      repeatable: false,
      platform: null,
      since: null,
      risk: "normal",
      editable: false,
      capability: referenceCapability("needs-editor"),
    },
    {
      key: "clipboard-read",
      description: "终端程序读取剪贴板时的处理方式。",
      defaultValues: ["ask"],
      currentValues: ["ask"],
      category: "privacy-security",
      kind: "select",
      choices: ["ask", "allow", "deny"],
      repeatable: false,
      platform: null,
      since: null,
      risk: "sensitive",
      editable: false,
      capability: referenceCapability("protected"),
    },
  ],
};

export const demoSnapshots: SnapshotInfo[] = [
  {
    id: "6fd13d7b-40e1-47f8-86e2-12cc63d4f26f",
    createdAtMs: Date.UTC(2026, 7, 3, 15, 42),
    revision: "90b41739c145ca68de4a52c946e88362cd42fb109dbf7c1a81f10e97de30c2be",
    sizeBytes: 1928,
  },
  {
    id: "adaf858b-50a8-4146-a54a-9d424f5ebc33",
    createdAtMs: Date.UTC(2026, 7, 2, 8, 18),
    revision: "747c55157b98ac9d070a6d2793e98b1d12dcb38cc84d729dd904330946af0498",
    sizeBytes: 1874,
  },
  {
    id: "bb9b05fb-a5d4-49b4-96dd-d5f16850af6a",
    createdAtMs: Date.UTC(2026, 6, 29, 4, 6),
    revision: "2be72338b4a60a01a8797f45ffb341c434efcc7f93f5a860284346857986bf34",
    sizeBytes: 1812,
  },
];
